services:
  db:
    image: postgres:12.21
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
    ports:
      - '5432:5432'
    volumes:
      - './local/postgresql/data:/var/lib/postgresql/data'
    secrets:
      - db_root_password

secrets:
  db_root_password:
    file: './local/db_root_password.txt'